theme: jekyll-theme-cayman

title: [Eric Mills]
description: [Software Engineer, Tech Entrepreneur, Y Combinator Alum, UIUC Alum]
show_downloads: ["false"]
#google_analytics: [Your Google Analytics tracking ID]`
