theme: jekyll-theme-minimal

title: [Eric Mills]
description: ["Software Engineer, Tech Entrepreneur, Y Combinator Alum, UIUC Alum"]
#google_analytics: [Your Google Analytics tracking ID]`

sass:
  sass_dir: assets/css
